### ISSUE TITLE
 When run => sudo python setup.py install [Error Shown]

### ISSUE THREAD

**Issue by MagicDemonn** [t-gitt/aircrack-ng-gui#2]
sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to aircrack_ng_gui.egg-info/requires.txt
writing aircrack_ng_gui.egg-info/PKG-INFO
writing top-level names to aircrack_ng_gui.egg-info/top_level.txt
writing dependency_links to aircrack_ng_gui.egg-info/dependency_links.txt
reading manifest file 'aircrack_ng_gui.egg-info/SOURCES.txt'
writing manifest file 'aircrack_ng_gui.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
byte-compiling build/bdist.linux-x86_64/egg/aircrack-ng-gui/aircrack-ng-gui.py to aircrack-ng-gui.pyc
  File "build/bdist.linux-x86_64/egg/aircrack-ng-gui/aircrack-ng-gui.py", line 231
    command_airmon_start= f"sudo airmon-ng start {interface}"
                                                            ^
SyntaxError: invalid syntax

installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
error: file '/home/ak/Downloads/aircrack-ng-gui/build/lib/aircrack-ng-gui/aircrack-ng-gui.py' does not exist

**Comment by t-gitt** [comment]
Hi, what's the output of `python --version`?
